version: '3'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes: 
      - .:/usr/src/app
    links:
      - db
    working_dir: "/usr/src/app"
    tty: true
    command: ["bash", "/usr/src/app/start.sh"]

  db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    
